# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
#  main:
#    web-application-type: none
  application:
    name: test
    display_time_zone: GMT+3
  jpa:
    open-in-view: false # register OpenEntityManagerInViewInterceptor
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        query:
          in_clause_parameter_padding: true
        temp.use_jdbc_metadata_defaults: false
        format_sql: false
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        event.merge.entity_copy_observer: allow
        default_batch_fetch_size: 20
        generate_statistics: false
        jdbc.time_zone: UTC
